New cstxsd distribution, simpler syntax for products and distributions
* New distribution for cstxsd including static inclusion of xerces_c.

* create_product_variables(), create_product_variable_list() deprecated
  in favor of new function create_version_variables(). Use of
  create_version_variables() is also encouraged for distributions to
  reduce the chance for versioning errors in build configuration files.

* New generated variables X_NAME to handle the case when the variable
  name is not the only thing we need to know (e.g. distinguishing Python
  2 from Python 3, or the art product from the art suite).

* New generated variable @DIST_BUILD_SPEC@ available for substitution
  into build configuration files: <dist-name>-<dist-dot-version>.

* New function distribution(<var-stem> [WITH_HTML]).

* Reduce the need for multi-line cut / paste / tweak for new
  distributions.

* Handle single or dual Python specification for distributions with
  generated shell code.

* Remove obsolete bootstrapCPack.cmake and supporting functions and
  macros.

* General improvement of documentation in bootstrapModules.cmake and
  *-cfg.in files.

diff --git a/bundle/nulite-cfg.in b/bundle/nulite-cfg.in
--- a/bundle/nulite-cfg.in
+++ b/bundle/nulite-cfg.in
@@ -1,49 +1,60 @@
-# build nu distribution
+########################################################################
+# Distribution build configuration for @DIST_BUILD_SPEC@
+#
+#   Build the Nu-Lite distribution.
+########################################################################
 
 basequal=${1}
 
-# specify version to bootstrap and setup ups
+# Specify version to bootstrap and setup UPS.
 check_ups @UPS_VERSION@
 
-build_bundle nulite_base-@NULITE_DOT_VERSION@ ${basequal} || return $?
+build_bundle @NULITE_BASE_NAME@-@NULITE_BASE_DOT_VERSION@ ${basequal} || return
 
-# check the build label here after building nulite_base
-[[ "${build_label}" == py2 ]] && pyqual=:${build_label}
+@INIT_PYQUAL_VARS@
 
 ensure_cetpkgsupport @CETPKGSUPPORT_VERSION@
 ensure_cetbuildtools @CETBUILDTOOLS_VERSION_LIST@
 ensure_support_package -f NULL studio @STUDIO_VERSION@
 
-build_bundle art-@ART_SUITE_DOT_VERSION@ ${basequal} || return $?
-build_cet canvas_root_io @CANVAS_ROOT_IO_VERSION@ ${basequal}${pyqual}
-build_cet art_root_io @ART_ROOT_IO_VERSION@ ${basequal}${pyqual}
+build_bundle @ART_SUITE_NAME@-@ART_SUITE_DOT_VERSION@ ${basequal} || return
+build_cet canvas_root_io @CANVAS_ROOT_IO_VERSION@ ${basequal}${pylabel}
+build_cet art_root_io @ART_ROOT_IO_VERSION@ ${basequal}${pylabel}
 
 if [[ -z "${version_set}" ]]; then
-  echo "ERROR: version set must be specified for artdaq_core"
+  echo "ERROR: version set must be specified for artdaq_core" 1>&2
   return 1
 fi
 
-# as of v1_07_00, artdaq_core is built with canvas and TRACE
+# As of v1_07_00, artdaq_core is built with canvas and TRACE.
+#
 # TRACE >= v3_14_00 needs buildFW >= 4.00.00 and cetmodules.
 if (( $(print_version | cut -d' ' -f 2 | cut -d. -f1) < 4)); then
-  echo "ERROR TRACE >= v3_14_00 needs buildFW >= 4.00.00" 1>&2
-  return 1;
+  echo "ERROR: TRACE >= v3_14_00 needs buildFW >= 4.00.00" 1>&2
+  return 1
 fi
 build_cet_null -DWANT_UPS=1 cetmodules @CETMODULES_VERSION@
 
 build_cet -p trace-git TRACE @TRACE_VERSION@ -nq-
 
-build_cet -p artdaq-core artdaq_core @ARTDAQ_CORE_VERSION@ ${basequal}${pyqual}:@version_set@
+build_cet -p artdaq-core artdaq_core @ARTDAQ_CORE_VERSION@ \
+  ${basequal}${pylabel}:@version_set@
 
-build_cet -p "ifdh-art/ifdh_art.git" ifdh_art @IFDH_ART_VERSION@ ${basequal}${pyqual}
-build_cet toyExperiment @TOYEXPERIMENT_VERSION@ ${basequal}${pyqual}:@version_set@
+build_cet -p "ifdh-art/ifdh_art.git" ifdh_art @IFDH_ART_VERSION@ \
+  ${basequal}${pylabel}
+build_cet toyExperiment @TOYEXPERIMENT_VERSION@ \
+  ${basequal}${pylabel}:@version_set@
 
-build_cet nusimdata @NUSIMDATA_VERSION@ ${basequal}${pyqual}
-build_cet nuevdb @NUEVDB_VERSION@ ${basequal}${pyqual}
-build_cet nug4 @NUG4_VERSION@ ${basequal}${pyqual}
-build_cet geant4reweight @GEANT4REWEIGHT_VERSION@ ${basequal}${pyqual}:@version_set@
-build_cet nugen @NUGEN_VERSION@ ${basequal}${pyqual}
-build_cet nutools @NUTOOLS_VERSION@ ${basequal}${pyqual}
-build_cet ppfx @PPFX_VERSION@ ${basequal}${pyqual}
+build_cet nusimdata @NUSIMDATA_VERSION@ ${basequal}${pylabel}
+build_cet nuevdb @NUEVDB_VERSION@ ${basequal}${pylabel}
+build_cet nug4 @NUG4_VERSION@ ${basequal}${pylabel}
+build_cet geant4reweight @GEANT4REWEIGHT_VERSION@ \
+  ${basequal}${pylabel}:@version_set@
+build_cet nugen @NUGEN_VERSION@ ${basequal}${pylabel}
+build_cet nutools @NUTOOLS_VERSION@ ${basequal}${pylabel}
+build_cet ppfx @PPFX_VERSION@ ${basequal}${pylabel}
 
-return 0
+# Local Variables:
+# mode: sh
+# eval: (sh-set-shell "bash")
+# End:
