first updates for art 3.05

diff --git a/bundle/nulite-cfg.in b/bundle/nulite-cfg.in
--- a/bundle/nulite-cfg.in
+++ b/bundle/nulite-cfg.in
@@ -7,21 +7,19 @@ check_ups @UPS_VERSION@
 
 build_bundle nulite_base-@NULITE_DOT_VERSION@ ${basequal} || return $?
 
+# check the build label here after building nulite_base
+[[ "${build_label}" == py2 ]] && pyqual=:${build_label}
+
 ensure_cetpkgsupport @CETPKGSUPPORT_VERSION@
 ensure_cetbuildtools @CETBUILDTOOLS_VERSION_LIST@
 ensure_support_package -f NULL studio @STUDIO_VERSION@
 
-build_cet cetlib_except @CETLIB_EXCEPT_VERSION@ ${basequal}
-build_cet hep_concurrency @HEP_CONCURRENCY_VERSION@ ${basequal}
-build_cet cetlib @CETLIB_VERSION@ ${basequal}
-build_cet -p fhicl-cpp fhiclcpp @FHICLCPP_VERSION@ ${basequal}
-build_cet messagefacility @MESSAGEFACILITY_VERSION@ ${basequal}
-build_cet canvas @CANVAS_VERSION@ ${basequal}
-build_cet canvas_root_io @CANVAS_ROOT_IO_VERSION@ ${basequal}
-build_cet art @ART_VERSION@ ${basequal}
+build_bundle art-@ART_SUITE_DOT_VERSION@ ${basequal} || return $?
+build_cet canvas_root_io @CANVAS_ROOT_IO_VERSION@ ${basequal}${pyqual}
+build_cet art_root_io @ART_ROOT_IO_VERSION@ ${basequal}${pyqual}
 
 if [[ -z "${version_set}" ]]; then
-  echo "ERROR: version set must be specified for ifdh_art and artdaq_core"
+  echo "ERROR: version set must be specified for artdaq_core"
   return 1
 fi
 
@@ -35,16 +33,17 @@ build_cet_null -DWANT_UPS=1 cetmodules @CETMODULES_VERSION@
 
 build_cet -p trace-git TRACE @TRACE_VERSION@ -nq-
 
-build_cet -p artdaq-core artdaq_core @ARTDAQ_CORE_VERSION@ ${basequal}:@version_set@
+build_cet -p artdaq-core artdaq_core @ARTDAQ_CORE_VERSION@ ${basequal}${pyqual}:@version_set@
 
-build_cet -p "ifdh-art/ifdh_art.git" ifdh_art @IFDH_ART_VERSION@ ${basequal}:${version_set}
-build_cet toyExperiment @TOYEXPERIMENT_VERSION@ ${basequal}:${version_set}
+build_cet -p "ifdh-art/ifdh_art.git" ifdh_art @IFDH_ART_VERSION@ ${basequal}${pyqual}
+build_cet toyExperiment @TOYEXPERIMENT_VERSION@ ${basequal}${pyqual}:@version_set@
 
-build_cet nusimdata @NUSIMDATA_VERSION@ ${basequal}
+build_cet nusimdata @NUSIMDATA_VERSION@ ${basequal}${pyqual}
 build_cet nuevdb @NUEVDB_VERSION@ ${basequal}${pyqual}
-build_cet nug4 @NUG4_VERSION@ ${basequal}
-build_cet geant4reweight @GEANT4REWEIGHT_VERSION@ ${basequal}:@version_set@
-build_cet nugen @NUGEN_VERSION@ ${basequal}
-build_cet nutools @NUTOOLS_VERSION@ ${basequal}
+build_cet nug4 @NUG4_VERSION@ ${basequal}${pyqual}
+build_cet geant4reweight @GEANT4REWEIGHT_VERSION@ ${basequal}${pyqual}:@version_set@
+build_cet nugen @NUGEN_VERSION@ ${basequal}${pyqual}
+build_cet nutools @NUTOOLS_VERSION@ ${basequal}${pyqual}
+build_cet ppfx @PPFX_VERSION@ ${basequal}${pyqual}
 
 return 0
